trigger:
  - main
pool:
  vmImage: Ubuntu-latest
stages:
  - stage: Build
    displayName: Build Angular Application QA Start
    jobs:
      - job: BuildApp
        displayName: Build Angular Project
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 16.x
            displayName: Install Node.js
          - script: |
              npm install -g @angular/cli
              npm install
              ng build # For Angular CLI v13+; use --prod for older versions
            displayName: Build Angular Application
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: dist/testdemo/browser
              artifactName: testdemo
              publishLocation: Container
            displayName: Publish Build Artifacts
  - stage: Deploy
    displayName: Deploy Angular Application to QA
    jobs:
      - job: DeployToQA
        displayName: Deploy to QA Environment
        environment: 'qa'
        steps:
          - script: echo "Starting deployment to QA environment..."
            displayName: Print Start Message
          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: vivektailang
              sourceFolder: $(Pipeline.Workspace)/testdemo/browser
              targetFolder: /var/www/html
            displayName: Copy Files to VM
          - task: SSH@0
            inputs:
              sshEndpoint: vivektailang
              script: |
                sudo systemctl restart apache2 # Adjust based on your web server
            displayName: Restart Web Server
